import type { Finding, LetterType, Submission } from '@prisma/client';
import { summarize } from '@/lib/status';

const AI_NOTICE =
  'This review was prepared with the assistance of an AI first-pass screening tool. The AI output is decision support only: the findings below were reviewed, triaged and adopted by the undersigned engineer, who is solely responsible for the final determination.';

const RULESET_NOTICE =
  'Rule references in this letter come from a demonstration rule set and are labelled as placeholders. They are not verified Canadian Electrical Code text and must be confirmed against the current code and applicable provincial amendments.';

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

export function letterTypeFor(findings: Finding[]): LetterType {
  return summarize(findings).confirmed > 0 ? 'DEFICIENCY' : 'APPROVAL';
}

export function buildLetter(submission: Submission, findings: Finding[]): { type: LetterType; body: string } {
  const engineer = process.env.REVIEWING_ENGINEER || 'Reviewing Engineer, P.Eng.';
  const t = summarize(findings);
  const type = letterTypeFor(findings);
  const lines: string[] = [];

  lines.push(type === 'APPROVAL' ? 'ELECTRICAL SAFETY REVIEW — APPROVAL LETTER (DRAFT)' : 'ELECTRICAL SAFETY REVIEW — NOTICE OF DEFICIENCY (DRAFT)');
  lines.push('');
  lines.push(`Date of letter:     ${formatDate(new Date())}`);
  lines.push(`Project:            ${submission.projectName}`);
  lines.push(`Submitted by:       ${submission.submitterName}`);
  lines.push(`Submission date:    ${formatDate(submission.submissionDate)}`);
  lines.push(`Document reviewed:  ${submission.fileName}`);
  lines.push('');

  if (type === 'APPROVAL') {
    lines.push('The submission listed above has been screened against the review checklist and no outstanding');
    lines.push('deficiencies were confirmed by the reviewing engineer. Subject to the notes below, the submission');
    lines.push('is recommended as ready for engineer sign-off.');
  } else {
    lines.push('The submission listed above has been reviewed and the following deficiencies were confirmed.');
    lines.push('A revised submission addressing each item is required before approval can be issued.');
  }
  lines.push('');

  const confirmed = findings.filter((f) => f.status === 'FAIL' && f.decision === 'CONFIRMED');
  if (confirmed.length > 0) {
    lines.push('CONFIRMED DEFICIENCIES');
    lines.push('');
    confirmed.forEach((f, i) => {
      lines.push(`${i + 1}. ${f.ruleTitle}`);
      lines.push(`   Reference: ${f.ruleCitation}`);
      lines.push(`   Finding:   ${f.explanation}`);
      if (f.evidence) lines.push(`   Basis:     ${f.evidence}`);
      lines.push('   Required:  Revise the submission to demonstrate compliance with the referenced requirement,');
      lines.push('              or provide supporting documentation showing the requirement is met.');
      if (f.decisionNote) lines.push(`   Reviewer note: ${f.decisionNote}`);
      lines.push('');
    });
  }

  const waived = findings.filter((f) => f.status === 'FAIL' && f.decision === 'WAIVED');
  if (waived.length > 0) {
    lines.push('ITEMS WAIVED BY THE REVIEWING ENGINEER');
    lines.push('');
    waived.forEach((f, i) => {
      lines.push(`${i + 1}. ${f.ruleTitle} — ${f.ruleCitation}`);
      lines.push(`   Reviewer note: ${f.decisionNote || '(no note provided)'}`);
      lines.push('');
    });
  }

  const insufficient = findings.filter((f) => f.status === 'INSUFFICIENT_DATA');
  if (insufficient.length > 0) {
    lines.push('ITEMS NOT VERIFIABLE FROM THE SUBMITTED DOCUMENTS');
    lines.push('');
    insufficient.forEach((f, i) => {
      lines.push(`${i + 1}. ${f.ruleTitle} — ${f.ruleCitation}`);
      lines.push(`   ${f.explanation}`);
      lines.push('');
    });
  }

  lines.push('REVIEW SUMMARY');
  lines.push('');
  lines.push(`Checklist items evaluated: ${t.total}`);
  lines.push(`Passed: ${t.passes}   Confirmed deficiencies: ${t.confirmed}   Waived: ${t.waived}   Dismissed as false positive: ${t.dismissed}   Insufficient data: ${t.insufficient}`);
  lines.push('');
  lines.push('NOTICES');
  lines.push('');
  lines.push(AI_NOTICE);
  lines.push('');
  lines.push(RULESET_NOTICE);
  lines.push('');
  lines.push('Final determination and sign-off:');
  lines.push('');
  lines.push(`${engineer}`);
  lines.push('Signature: ______________________________    Date: ______________');
  lines.push('');
  lines.push('(Draft generated by the Electrical Safety Approval Assistant proof of concept. Not valid until signed.)');

  return { type, body: lines.join('\n') };
}
